BUILD_HOME   := $(shell dirname `cd ../../; pwd`)
Project      := reg_utils
Package      := rwreg
ShortPackage := rwreg
LongPackage  := rwreg
PackageName  := $(ShortPackage)
PackagePath  := $(shell pwd)
PackageDir   := pkg/$(ShortPackage)

RWREG_VER_MAJOR=1
RWREG_VER_MINOR=0
RWREG_VER_PATCH=0

include $(BUILD_HOME)/$(Project)/config/mfCommonDefs.mk
